# -*- coding: utf-8 -*-
"""0424_HW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KFvj9VIDKXejCKq3-l6WmwYrv84gB3fr
"""

n = int(input("숫자를 입력하세요: "))

def print_triangle(n):
  for i in range(1, n+1): 
    for y in range(i): 
      print("*", end="")
    print()
print("1. 왼쪽 정렬 삼각형")
print_triangle(n)

def print_reversed_triangles(n):
  for i in range(1, n+1):
    for j in range(n-i): 
      print(" ", end="")
    for j in range(i): 
      print("*", end="")
    print()
print("2. 오른쪽 정렬 삼각형")
print_reversed_triangles(n)

def print_tree(n):
  for i in range(1, n+1):
    for j in range(n+1-i): 
      print(" ", end="")
    for j in range(2*i-1): 
      print("*", end="")
    print()
print("3. 가운데 정렬 삼각형")
print_tree(n)

def print_diamond(n):
  for i in range(1, n+1):
    print(' ' * (n - i) + '*' * (2 * i - 1)) 
  if n == i:
    for i in range(n-1, 0, -1):
      print(' ' * (n - i) + '*' * (2 * i - 1))
print("4. 다이아몬드")
print_diamond(n)